### ISSUE TITLE
Service(매체) Feature Embedding

### ISSUE THREAD

**Issue by youngju-oh** [teamdable/cb_feature_and_total_model#2]
- service embedding 의 효과적 생성 방법을 탐구한다
- service 가 광고 ctr 에 영향을 주는지, service feature 와 광고간의 내용적 상관관계가 ctr 에 영향을 주는지 실험을 통해 확인한다.

**Comment by youngju-oh** [comment]
- [ ] 매체의 기사화 ideation
  - bert embedding -> 차원 축소
- [ ] ctr 과의 상관성, 광고와의 관계와 ctr 간의 상관성 확인
  - deepfm model 활용

**Comment by youngju-oh** [comment]
4/5~6 진행중
- [ ] 구현체 코드, 테스트 코드 검토
- [ ] 모델 학습용으로 데이터 전처리
- [ ] 적용

**Comment by yongho-ha** [comment]
>   * bert embedding -> 차원 축소

@youngju-oh 가물 가물해서, 요때 차원 축소는 어떤 방법을 쓰신다고 했던가용?

**Comment by youngju-oh** [comment]
@yongho-ha umap이요!

**Comment by youngju-oh** [comment]
deep fm 로 service embedding, ad content embedding 을 feature 로 ctr 예측 테스트
-> epoch 늘릴수록 loss값이 감소하기는 하지만 service_id 기준으로 aggregation 한터라, feature 의 성능을 평가하기엔 데이터가 매우 부족한 상태인걸로 보임(1달치 data aggregation : 총 20514건 / epoch 10회 도는데에 1분이 안걸림)
-> item feature 에 service feature 를 추가한 후 loss 값이 더 줄어드는지 비교해 보는 등 다른 방법이 필요할 수도 있을 것 같음
-> 일단 item embedding 에서 적용했던 방법대로 그래프 그려볼 예정

**Comment by youngju-oh** [comment]
service embedding, ad content embedding 을 feature 로 ctr 예측 테스트
- deep fm 대신 lgbm 으로 확인 (service id 기준 aggregation 후의 데이터라 그 수가 많지 않아서 deep fm 을 학습시키기엔 부적합)
- 데이터 불균형 맞춘 후, auc 계산하는 로직 작성(index 실수때문에 이게 생각보다 오래걸렸음 ㅠ)
- 매우 낮거나 매우 높은 ctr 기준에서는 높은 구분력을 보이나, 중간정도의 ctr기준에서는 비교적 낮은 구분력(auc 0.663)을 보이는 것을 확인함
service embedding 방법에서 어떤 것을 변경할 수 있는지 다시한번 정리해보고, 이 중 가장 유효해 보는 것을 변경 후 다시 auc 실험하는 과정을 반복할 예정

**Comment by youngju-oh** [comment]
dimension reduction 알고리즘 비교 (umap을 중심으로)
- umap 논문 : https://arxiv.org/abs/1802.03426
- 퍼지이론 기반이라, 논문 자체를 이해하기는 쉽지 않음... (저는 너무 어려웠어요;;)
- 아래 유튜브의 설명이 적절한 듯
  - umap 이 왜 best 인가(matrix factorization 기반 알고리즘 (pca)과 neighbor 기반 알고리즘(t-sne, umap)간의 비교) : https://www.youtube.com/watch?v=6BPl81wGGP8
  - umap 과 t-sne 의 비교 : https://www.youtube.com/watch?v=4NlvatkpV3s

**Comment by youngju-oh** [comment]
1. sentence embedding 방법을 바꿀 필요가 없을지도 ctr 기준에 따른 auc를 확인해본 결과 ctr 기준 0.2 내에서는 최소 auc 가 0.65로 성능이 나쁘지 않은 것으로 보임
  - https://www.notion.so/dableglobal/service-embedding-test-e19d7924b14246b689c60c029b5c6a98 의 그래프 참조
2. 그럼에도 일단은 sentence embedding 기법을 바꿀 여지가 있는지 확인
  - 개선 가능 포인트 정리 : https://www.notion.so/dableglobal/service-embedding-58b168d460364c01aa4ae6600ce749a7
  - dimension reduction 방법론 정리 : https://www.notion.so/dableglobal/Dimension-reduction-b98f1eb051f14c819929bdadcc73236e
  - 세가지 개선 가능 포인트(1. embedding 방법, 2. vector average 방법, 3. dimension reduction 방법) 중 
    1. embedding 방법은 현상황에서 bert가 최선인듯
    2. sentence vector 에 대해 기사 인기도에 따라 weighted average 적용 등이 가능할 듯
    3. 최적화되지 않은 umap 과 pca를 비교해볼 수 있을 듯
      - why? 
        - umap 이 차원 감소 기법 중 best performance 를 낸다고 알려져 있는것을 확인
        - 단, umap 은 hyper parameter 가 필요한데에 비해 pca 는 필요 없음
        - 자동화시켰을 경우 umap 의 hyper parameter 를 그때그때 최적화시킬 수는 없기 때문에 hyper parameter 를 최적화시키지 않은 umap 과 pca 의 성능을 비교하여 더 나은 결과를 보여주는 결과를 활용할 수 있을 것으로 보임.

**Comment by yongho-ha** [comment]
DM에서 말씀드렸던대로, 이미 성능이 훌륭하므로 PCA 탭핑하는 정도로 하고 1차 마무리 갑시당

**Comment by youngju-oh** [comment]
1. pca 시도 결과 
  - umap 에 비해 모든 지점에서 높은 auc 를 보이는 듯
  - 근데 그 수치가 너무 높아서,,, 일단 왜 이렇게 높게 측정되는지 확인해볼 필요가 있을 듯함 (service 갯수, content 갯수, 각각 service 만 넣었을때, content 만 넣었을때 결과가 어떤지... 오늘까지만)
  - https://www.notion.so/dableglobal/service-embedding-test-e19d7924b14246b689c60c029b5c6a98
2. 문서 정리 예정 (service embedding 전체 방법 정리, pca 와 umap 간의 비교 정리)

**Comment by youngju-oh** [comment]
service embedding 문서 작성 완료
- https://www.notion.so/dableglobal/Service-id-embedding-vector-5c38c7120fde4cc7a75f0db95751c953
